owner:
  group: 35058813 ## "<<!TEMPLATE!>><<provide here group id>>"

state:
  remote:
    region: eu-north-1
    bucket: r0rnor-mantle-states
    key: <<!TEMPLATE!>><<provide-there-game-name>>

environments:
  - label: prod
    branches:
      - main
    targetAccess: private

target:
  experience:
    configuration:
      playableDevices: [computer, console, phone, tablet]
      privateServers:
        price: 0
      enableStudioAccessToApis: true
      avatarType: r15
      avatarAnimationType: playerChoice
    spatialVoice:
      enabled: true
    places:
      start:
        file: Lobby.rbxlx
        configuration:
          name: <<!TEMPLATE!>><<provide here game name>>
          description: you only have 24^2 hours to lose weight
          maxPlayerCount: 8
          allowCopying: false
      mainGame:
        file: MainGame.rbxlx
        configuration:
          name: <<!TEMPLATE!>><<provide here game name>>
          description: you only have 24^2 hours to lose weight
          maxPlayerCount: 8
          allowCopying: false
    products:
    passes: